services:
  app:
    container_name: app-dev
    image: node:22-alpine
    command: >
      sh -c "
        corepack enable &&
        pnpm install &&
        pnpm dev
      "
    working_dir: /app
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres123@postgres:5432/server_node_exercise
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Ignore node_modules to avoid pnpm install issues
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
